
# Don't forget to set SPRING_DATA_MONGODB_URI
# SPRING_DATA_MONGODB_URI=mongodb+srv://<user>:<password>@cluster0.fydqtzw.mongodb.net/perlettes?ssl=true&authSource=admin&retryWrites=true&w=majority


#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://user:<password>@cluster0.fydqtzw.mongodb.net/perlettes?ssl=true&authSource=admin&retryWrites=true&w=majority
#      database: perlettes